# Home directory — personal files, scripts, dotfiles
PATHS="/home/will"
KEEP_DAILY=14
KEEP_WEEKLY=8
KEEP_MONTHLY=24
OFFSITE=true

EXCLUDES="
**/.cache
**/node_modules
**/.next
**/__pycache__
**/.local/share/Trash
**/.npm/_cacache
**/.dropbox-dist
**/.dropbox-dist-old-*
**/Dropbox
"
