parity /Volumes/MediaParity1/snapraid.parity
2-parity /Volumes/MediaParity2/snapraid.parity
3-parity /Volumes/MediaParity3/snapraid.parity
content /snapraid/snapraid.content
content /Volumes/MediaB/snapraid.content
content /Volumes/MediaC/snapraid.content
content /Volumes/MediaD/snapraid.content
content /Volumes/MediaE/snapraid.content
content /Volumes/MediaF/snapraid.content
data d1 /Volumes/MediaA/
data d2 /Volumes/MediaB/
data d3 /Volumes/MediaC/
data d4 /Volumes/MediaD/
data d5 /Volumes/MediaE/
data d6 /Volumes/MediaF/
data d7 /Volumes/MediaG/
data d8 /Volumes/MediaH/
data d9 /Volumes/MediaI/
data d10 /Volumes/MediaJ/
#data d9 /Volumes/MediaSpare/
exclude /Plex Media Server/
exclude /lost+found/
exclude /recycling_bin/
exclude Optimized/
exclude incoming_nzb/
exclude partially_downloaded/
exclude program_state/
exclude /Downloads/mega/
exclude /Downloads/downloading/
exclude /Downloads/jdownload/
exclude /timeshift/
exclude *.db-wal
exclude *.db-shm
exclude *.log
exclude *.part
exclude *.encrypted
autosave 100
